// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

/*
Package go_micro_srv_consignment is a generated protocol buffer package.

It is generated from these files:
	proto/consignment/consignment.proto

It has these top-level messages:
	Consignment
	Container
	Response
*/
package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight      int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers  []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	VesselId    string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId" json:"vessel_id,omitempty"`
}

func (m *Consignment) Reset()                    { *m = Consignment{} }
func (m *Consignment) String() string            { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()               {}
func (*Consignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	Origin     string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	UserId     string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created     bool         `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Consignment *Consignment `protobuf:"bytes,2,opt,name=consignment" json:"consignment,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.consignment.ShippingService/CreateConsignment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.ShippingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.consignment.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShippingService_CreateConsignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}

func init() { proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0xa4, 0xef, 0x66, 0x23, 0x81, 0xf0, 0x01, 0x22, 0x38, 0x50, 0xa5, 0x42, 0xea, 0xc9, 0x48,
	0xe5, 0x13, 0x72, 0x40, 0xbd, 0xba, 0x1f, 0x00, 0xc5, 0x59, 0xa5, 0x2b, 0x11, 0x3b, 0xb2, 0xdd,
	0xf2, 0x6d, 0xfc, 0x1d, 0xae, 0xd3, 0x50, 0x4b, 0xa8, 0x88, 0xdb, 0xce, 0xce, 0x4e, 0x66, 0x46,
	0x31, 0xcc, 0x1b, 0xa3, 0x9d, 0x7e, 0x92, 0x5a, 0x59, 0xaa, 0x54, 0x8d, 0xca, 0xc5, 0x33, 0x0f,
	0x2c, 0xcb, 0x2a, 0xcd, 0x6b, 0x92, 0x46, 0x73, 0x6b, 0xf6, 0x3c, 0xe2, 0xf3, 0xaf, 0x1e, 0xa4,
	0xc5, 0x09, 0xb3, 0x4b, 0xe8, 0x53, 0x99, 0xf5, 0x66, 0xbd, 0x45, 0x22, 0xfc, 0xc4, 0x66, 0x90,
	0x96, 0x68, 0xa5, 0xa1, 0xc6, 0x91, 0x56, 0x59, 0x3f, 0x10, 0xf1, 0x8a, 0xdd, 0xc0, 0xf8, 0x13,
	0xa9, 0xda, 0xba, 0x6c, 0xe0, 0xc9, 0x91, 0x38, 0x22, 0x56, 0x00, 0x78, 0x23, 0xb7, 0x21, 0x85,
	0xc6, 0x66, 0xc3, 0xd9, 0x60, 0x91, 0x2e, 0xe7, 0xfc, 0x5c, 0x10, 0x5e, 0x74, 0xb7, 0x22, 0x92,
	0xb1, 0x7b, 0x48, 0xf6, 0x68, 0x2d, 0x7e, 0xbc, 0xfa, 0x54, 0xa3, 0x60, 0x3e, 0x6d, 0x17, 0xab,
	0x32, 0xaf, 0x21, 0xf9, 0x51, 0xfd, 0x0a, 0xfe, 0x00, 0xa9, 0xdc, 0x59, 0xa7, 0x6b, 0x34, 0x07,
	0x6d, 0x1b, 0x1c, 0xba, 0xd5, 0xaa, 0x3c, 0xe4, 0xd6, 0x86, 0x2a, 0x52, 0x21, 0x77, 0x22, 0x8e,
	0x88, 0xdd, 0xc2, 0x64, 0x67, 0x5b, 0xd1, 0xb0, 0x25, 0x0e, 0x30, 0xd8, 0x4d, 0x05, 0xda, 0xc6,
	0x67, 0x46, 0x96, 0xc1, 0x44, 0x1a, 0xdc, 0x38, 0x6c, 0x2d, 0xa7, 0xa2, 0x83, 0xec, 0xc5, 0xfb,
	0x9e, 0x6a, 0x05, 0xdf, 0x74, 0xf9, 0xf8, 0x67, 0xef, 0x6e, 0x16, 0xb1, 0x72, 0x69, 0xe1, 0x6a,
	0xbd, 0xa5, 0xa6, 0x21, 0x55, 0xad, 0xd1, 0xec, 0x49, 0x22, 0x7b, 0x83, 0xeb, 0x22, 0xd8, 0xc4,
	0x7f, 0xec, 0x7f, 0xdf, 0xbe, 0xcb, 0xcf, 0x9f, 0x75, 0xad, 0xf2, 0x8b, 0xf7, 0x71, 0x78, 0x2f,
	0xcf, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x12, 0xe8, 0xcf, 0xde, 0x56, 0x02, 0x00, 0x00,
}
